### ISSUE TITLE
Installation issue on MacOS/OSX

### ISSUE THREAD

**Issue by antman2** [lamogui/ogre_blender_importer#2]
I attempted to install ogre_blender_importer in to Blender 2.77 using the following Terminal commands:

```
$ cd ~/Library/Application\ Support/Blender/2.77/
$ mkdir scripts
$ cd scripts
$ mkdir addons
$ cd addons
$ git clone https://github.com/lamogui/ogre_blender_importer.git
```

When going to Blender's File > User Preferences... > Add-ons > Import-Export and ticking "Import-Export: Ogre Blender Importer" I immediately got the following Python exception trace:

```
Traceback (most recent call last):
 File "/Users/username/Library/Application Support/Blender/2.77/scripts/addons/ogre_blender_imports/__init__.py", line 14, in <module> from OgreMeshSerializer import *
ImportError: No module named 'OgreMeshSerializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "OgreMeshSerializer.py", line 17, in <module>
  except ImportError as e:
ImportError: No module named 'OgreMesgSerializerImpl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/Applications/blender.app/Contents/MacOS/..Resources/2.77/scripts/modules/addon_utils.py", line 330, in enable mod = __import__(module_name)
 File "/Users/username/Library/Application Support/Blender/2.77/scripts/addons/ogre_blender_importer/__init__py", line 21, in <module>
  srcfile="OgreMesgSerializer.py"; exec(compile(open(os.path.join(directory,srcfile)).read(), srcfile, 'exec'))
 File "OgreMeshSerializer.py", line 26, in <module>
 File "/Applications/blender.app/Contents/MacOS/../Resources/2.77/python/lib/python3.5/encodings/ascii.py", line 26, in decode
  return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xC3 in position 2110: ordinal not in range(128)
```

In OgreMesgSerializerImpl.py, line 52 has:
`        vSemantic = self._readUShorts(stream, 1)[0]; #Utilité du vertex`

When I changed it to the following the add-on was loaded successfully when ticked:
`        vSemantic = self._readUShorts(stream, 1)[0]; #Vertex utility`

Seems that the Python library that ships with Blender for MacOS/OSX doesn't like UTF-8 characters, or maybe the Blender team hasn't configured it correctly. :(

**Comment by lamogui** [comment]
I don't have OSX so I can't test... 
Thx for feedback if you have time to do this now, if you do a little patch (remiving the "é" by "e") please pull request it I will be happy to merge
